### ISSUE TITLE
做的好

### ISSUE THREAD

**Issue by miaopeng233** [tylearymf/AutomaticGamepad#1]

**Comment by helloldt** [comment]
你好，L2与R2按键似乎没用，trigger("l2", 1)似乎对ps4不奏效

**Comment by tylearymf** [comment]
> 你好，L2与R2按键似乎没用，trigger("l2", 1)似乎对ps4不奏效

那可能ps4下不行的吧，只在ps5下测试过🤣

**Comment by tylearymf** [comment]
@lwoldt 你试下用界面上的小手柄看看有没有效

**Comment by helloldt** [comment]
您好，试过小手柄了，也是无效的





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tylearymf/AutomaticGamepad"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月5日(星期一) 晚上6:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tylearymf/AutomaticGamepad] 做的好 (Issue #1)





 
@lwoldt 你试下用界面上的小手柄看看有没有效

**Comment by tylearymf** [comment]
我没有ps4，调试不了，你可以clone工程，调试下看看

**Comment by helloldt** [comment]
您好，PlaystationGamepad.cs这个类中
&nbsp; &nbsp;public string LeftStickButton = "l3";
&nbsp; &nbsp;public string RightStickButton = "r3";

&nbsp;&nbsp; { Trigger_L2, (GamepadButton)DualShock4Button.TriggerLeft },
&nbsp; &nbsp;{ Trigger_R2, (GamepadButton)DualShock4Button.TriggerRight },

是DualShock4Button.TriggerLeft还是(GamepadTrigger)DualShock4Slider.LeftTrigger
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tylearymf/AutomaticGamepad"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月5日(星期一) 晚上8:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tylearymf/AutomaticGamepad] 做的好 (Issue #1)





 
我没有ps4，调试不了，你可以clone工程，调试下看看

**Comment by helloldt** [comment]
另：
_jscode = "//sleep(200)\r\n//triggerstate(\"l1\", 1)\r\n//dpadstate(\"left\", true)\r\nbutton(\"l1\",1000)\r\nsleep(200)\r\nbutton(\"r1\",200)\r\nsleep(200)";
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; var codeObj = m_ScriptEngine.Compile(_jscode);


&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; m_ExecuteCount++;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; if (_jscode != "")
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; var code = (V8Script)codeObj;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; m_ScriptEngine.Execute(code);


&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }

可在前面加入文字识别与图像对比
我已使用Tesseract实现文字识别，检测耗时大约 50ms左右，很适合该项目




另外：
在进程搜索部分可供游客自行选择ps远程，因为有时候会有多个远程窗口进行活动
&nbsp; &nbsp;var text = textBox1.Text;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; if (string.IsNullOrWhiteSpace(text))
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; MessageBox.Show(Language.GetString(nameof(LanguageNames.title_cannot_empty)));
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; return;
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; textBox2.Text = "";
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; var handle = GetProcessWindow(text);
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; foreach (var handles in handle)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; {
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; textBox3.Items.Add(handles.ToInt32().ToString());
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; textBox2.Text = textBox2.Text + "&nbsp; " + handles.ToInt32().ToString();
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; //Gamepad.Handle = handle[0];
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tylearymf/AutomaticGamepad"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月5日(星期一) 晚上8:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tylearymf/AutomaticGamepad] 做的好 (Issue #1)





 
我没有ps4，调试不了，你可以clone工程，调试下看看

**Comment by helloldt** [comment]
是否能加您微信，关于ps4 的l2,r2键想和您探讨，我本地有环境




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tylearymf/AutomaticGamepad"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月5日(星期一) 晚上8:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tylearymf/AutomaticGamepad] 做的好 (Issue #1)





 
我没有ps4，调试不了，你可以clone工程，调试下看看

**Comment by tylearymf** [comment]
@lwoldt 你留下qq号，我加下你

**Comment by helloldt** [comment]
3513587960



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月6日(周二) 凌晨0:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tylearymf/AutomaticGamepad] 做的好 (Issue #1)




 
@lwoldt 你留下qq号，我加下你

**Comment by helloldt** [comment]
您的文档好像没有加l2和r2按键



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月5日(周一) 晚上6:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tylearymf/AutomaticGamepad] 做的好 (Issue #1)




  
你好，L2与R2按键似乎没用，trigger("l2", 1)似乎对ps4不奏效
  
那可能ps4下不行的吧，只在ps5下测试过🤣

**Comment by tylearymf** [comment]
> 您的文档好像没有加l2和r2按键

有的呀，在触发器那一项
