### ISSUE TITLE
学习请教

### ISSUE THREAD

**Issue by Rgcsh** [tylearymf/AutomaticGamepad#2]
请问大佬 具体技术原理能分享一下吗? 技术可行性上请问 能用python在mac上实现吗?

**Comment by tylearymf** [comment]
> 请问大佬 具体技术原理能分享一下吗? 技术可行性上请问 能用python在mac上实现吗?

不支持呢，用的是这个[虚拟手柄库](https://github.com/ViGEm/ViGEmBus)，可以看看这个问题：https://github.com/ViGEm/ViGEmBus/issues/98
你可以找找mac下的相关软件，看看有没有可编程的

**Comment by Rgcsh** [comment]
好的,非常感谢
