### ISSUE TITLE
请问windows系统是要求 win10吗?

### ISSUE THREAD

**Issue by Rgcsh** [tylearymf/AutomaticGamepad#3]

**Comment by tylearymf** [comment]
是的，项目里面自带的驱动是只支持win10以上的，如果要支持win10以下的，用这个驱动安装 https://github.com/ViGEm/ViGEmBus/releases/download/setup-v1.16.116/ViGEmBus_Setup_1.16.116.exe

**Comment by Rgcsh** [comment]
已完美操作,前人栽树后人乘凉
